# Generated by Django 4.2.5 on 2023-09-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_curing',
            name='Status',
            field=models.CharField(blank=True, choices=[('Approve', 'Approve'), ('Not Approve', 'Not Approve')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='structural_element',
            name='Time_Bet_TwoCuring',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
