# Generated by Django 4.2.5 on 2023-09-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curingapp', '0002_alter_schedule_curing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_curing',
            name='Image_Of_Curing',
            field=models.ImageField(blank=True, null=True, upload_to='curing_images/'),
        ),
    ]
