# Generated by Django 4.1.7 on 2023-09-25 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curingapp', '0004_alter_structural_element_time_bet_twocuring'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_concreting',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
